# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Userscript Auto Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup env
        run: |
          echo 'BUILD_PATH="../release"' > ./scripts/.env 
          echo 'VITE_BUILD_PATH="../../release"' > ./packages/core/.env
          echo 'VITE_BUILD_PATH="../../release"' > ./packages/scripts/.env
      - name: Install Dependencies
        run: |
          npm install pnpm -g
          pnpm install -w
          cd packages/scripts
          pnpm install
          cd ../../
          npm run tsc
      - name: Build ocs scripts
        run: npm run build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifactContentType: 'html/text'
          artifacts: './release/core.js,./release/ocs.user.js,./release/ocs.common.user.js'
          bodyFile: './CHANGELOG_CURRENT.md'
