# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "4.0" ]
  pull_request:
    branches: [ "4.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
       npm install pnpm -g
       pnpm install -w
       cd packages/scripts
       pnpm install
       cd ../../
       npm run tsc
    - name: Build ocs scripts
      run: npm run build:core
    - name: Upload Artifact 
      uses: actions/upload-artifact@v3
      with:
        name: ocs-scripts-release
        path: dist/**/*.js
    - name: Upload Userscript 
      uses: actions/upload-artifact@v3
      with:
        name: ocs-userscript
        path: dist/ocs.user.js
